--- 
- 
  hosts: client ###this is the inventory
  vars:
     mysql_user: "root"
     mysql_root_password: "StrongRootPassword!"
     python_mysql: "{{ 'python3-mysqldb' if ansible_distribution|lower in ['debian', 'ubuntu'] else 'python3-PyMySQL' }}"

  tasks:
      - name: Installing MariaDB Server
        package:
          name: mariadb-server
          state: latest
          update_cache: yes

      - name: Installing python_mysql
        package:
          name: "{{ python_mysql }}"
          state: present
          update_cache: yes

      - name: start and enable mariadb server
        service:
          name: mariadb
          enabled: true
          state: started
    ####we are going to delete all the default user and password
      - name: Delete all anonymous SQL user accounts
        mysql_user:
          user: "" 
          host_all: yes
          state: absent

      - name: Remove the SQL test database
        mysql_db:
          db: "test"
          state: absent

      - name: Change root user password on first run
        mysql_user: user=root password="{{mysql_root_password}}" host=localhost 
        register: mysql_secure
 
      - debug:
          var: mysql_secure
